require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProgrammingLanguagesController do

  # This should return the minimal set of attributes required to create a valid
  # ProgrammingLanguage. As you add validations to ProgrammingLanguage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProgrammingLanguagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all programming_languages as @programming_languages" do
      programming_language = ProgrammingLanguage.create! valid_attributes
      get :index, {}, valid_session
      assigns(:programming_languages).should eq([programming_language])
    end
  end

  describe "GET show" do
    it "assigns the requested programming_language as @programming_language" do
      programming_language = ProgrammingLanguage.create! valid_attributes
      get :show, {:id => programming_language.to_param}, valid_session
      assigns(:programming_language).should eq(programming_language)
    end
  end

  describe "GET new" do
    it "assigns a new programming_language as @programming_language" do
      get :new, {}, valid_session
      assigns(:programming_language).should be_a_new(ProgrammingLanguage)
    end
  end

  describe "GET edit" do
    it "assigns the requested programming_language as @programming_language" do
      programming_language = ProgrammingLanguage.create! valid_attributes
      get :edit, {:id => programming_language.to_param}, valid_session
      assigns(:programming_language).should eq(programming_language)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProgrammingLanguage" do
        expect {
          post :create, {:programming_language => valid_attributes}, valid_session
        }.to change(ProgrammingLanguage, :count).by(1)
      end

      it "assigns a newly created programming_language as @programming_language" do
        post :create, {:programming_language => valid_attributes}, valid_session
        assigns(:programming_language).should be_a(ProgrammingLanguage)
        assigns(:programming_language).should be_persisted
      end

      it "redirects to the created programming_language" do
        post :create, {:programming_language => valid_attributes}, valid_session
        response.should redirect_to(ProgrammingLanguage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved programming_language as @programming_language" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProgrammingLanguage.any_instance.stub(:save).and_return(false)
        post :create, {:programming_language => { "name" => "invalid value" }}, valid_session
        assigns(:programming_language).should be_a_new(ProgrammingLanguage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProgrammingLanguage.any_instance.stub(:save).and_return(false)
        post :create, {:programming_language => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested programming_language" do
        programming_language = ProgrammingLanguage.create! valid_attributes
        # Assuming there are no other programming_languages in the database, this
        # specifies that the ProgrammingLanguage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProgrammingLanguage.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => programming_language.to_param, :programming_language => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested programming_language as @programming_language" do
        programming_language = ProgrammingLanguage.create! valid_attributes
        put :update, {:id => programming_language.to_param, :programming_language => valid_attributes}, valid_session
        assigns(:programming_language).should eq(programming_language)
      end

      it "redirects to the programming_language" do
        programming_language = ProgrammingLanguage.create! valid_attributes
        put :update, {:id => programming_language.to_param, :programming_language => valid_attributes}, valid_session
        response.should redirect_to(programming_language)
      end
    end

    describe "with invalid params" do
      it "assigns the programming_language as @programming_language" do
        programming_language = ProgrammingLanguage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProgrammingLanguage.any_instance.stub(:save).and_return(false)
        put :update, {:id => programming_language.to_param, :programming_language => { "name" => "invalid value" }}, valid_session
        assigns(:programming_language).should eq(programming_language)
      end

      it "re-renders the 'edit' template" do
        programming_language = ProgrammingLanguage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProgrammingLanguage.any_instance.stub(:save).and_return(false)
        put :update, {:id => programming_language.to_param, :programming_language => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested programming_language" do
      programming_language = ProgrammingLanguage.create! valid_attributes
      expect {
        delete :destroy, {:id => programming_language.to_param}, valid_session
      }.to change(ProgrammingLanguage, :count).by(-1)
    end

    it "redirects to the programming_languages list" do
      programming_language = ProgrammingLanguage.create! valid_attributes
      delete :destroy, {:id => programming_language.to_param}, valid_session
      response.should redirect_to(programming_languages_url)
    end
  end

end
